# Generated by Django 4.0.6 on 2022-07-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='description',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
    ]
