# Generated by Django 4.0.6 on 2022-07-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageClass',
        ),
    ]
