# Generated by Django 4.0.6 on 2022-07-05 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0001_initial'),
        ('csgo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csplayer',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='csteam',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='eventtier',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Event Tier', 'verbose_name_plural': 'Event Tiers'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Event Type', 'verbose_name_plural': 'Event Types'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Map', 'verbose_name_plural': 'Maps'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='singlemapmatch',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Single Map Match', 'verbose_name_plural': 'Single Map Matches'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
        migrations.AddField(
            model_name='csteam',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='globalapp.country'),
        ),
    ]
