# Generated by Django 4.0.6 on 2022-07-04 21:09

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0002_map_playersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Tier',
                'verbose_name_plural': 'Event Tiers',
                'db_table': 'csgo_event_tiers',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'db_table': 'csgo_event_types',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_1_score', models.PositiveIntegerField(default=0)),
                ('team_2_score', models.PositiveIntegerField(default=0)),
                ('map_pool', django_jsonform.models.fields.JSONField(blank=True)),
                ('aftermath', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'csgo_matches',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SingleMapMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_1_score', models.PositiveIntegerField(default=0)),
                ('team_2_score', models.PositiveIntegerField(default=0)),
                ('map_number', models.PositiveIntegerField(default=1)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_match_finished', models.BooleanField(default=False)),
                ('players_stats', django_jsonform.models.fields.JSONField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csgo.map')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csgo.match')),
                ('mvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csgo.player')),
                ('team_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_match_team_1', to='csgo.team')),
                ('team_1_players', models.ManyToManyField(blank=True, related_name='team_1_players', to='csgo.player')),
                ('team_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_match_team_2', to='csgo.team')),
                ('team_2_players', models.ManyToManyField(blank=True, related_name='team_2_players', to='csgo.player')),
            ],
            options={
                'verbose_name': 'Single Map Match',
                'verbose_name_plural': 'Single Map Matches',
                'db_table': 'csgo_single_map_matches',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('abbr', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('social_media', django_jsonform.models.fields.JSONField(blank=True)),
                ('event_format', models.TextField(blank=True)),
                ('total_matches', models.PositiveIntegerField(default=16)),
                ('match_schedule', django_jsonform.models.fields.JSONField(blank=True)),
                ('total_teams', models.PositiveIntegerField(default=22)),
                ('prize_pool', models.CharField(blank=True, max_length=20)),
                ('prize_distribution', django_jsonform.models.fields.JSONField(blank=True)),
                ('teams_stats', django_jsonform.models.fields.JSONField(blank=True)),
                ('players_stats', django_jsonform.models.fields.JSONField(blank=True)),
                ('broadcasters', django_jsonform.models.fields.JSONField(blank=True)),
                ('talent', django_jsonform.models.fields.JSONField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csgo.eventtier')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csgo.eventtype')),
                ('maps', models.ManyToManyField(blank=True, to='csgo.map')),
                ('participant_teams', models.ManyToManyField(blank=True, to='csgo.team')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'db_table': 'csgo_tournaments',
                'ordering': ['updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='PlayerSettings',
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csgo.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_team_1', to='csgo.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_team_2', to='csgo.team'),
        ),
    ]
