# Generated by Django 4.0.6 on 2022-07-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0002_remove_country_created_at_remove_country_description_and_more'),
        ('csgo', '0003_csplayer_rank_alter_cstournament_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='csplayer',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='globalapp.playersetting'),
        ),
    ]
