# Generated by Django 4.0.6 on 2022-07-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0004_match_is_match_finished_match_mvp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
