# Generated by Django 4.0.6 on 2022-07-04 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0005_match_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlemapmatch',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
