# Generated by Django 4.0.6 on 2022-07-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0006_singlemapmatch_title_alter_map_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtier',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='singlemapmatch',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_match_team_1', to='csgo.team'),
        ),
        migrations.AlterField(
            model_name='singlemapmatch',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_match_team_2', to='csgo.team'),
        ),
    ]
