# Generated by Django 4.0.6 on 2022-07-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0001_initial'),
        ('csgo', '0007_alter_eventtier_slug_alter_eventtype_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='globalapp.pcspec'),
        ),
    ]
