# Generated by Django 4.0.6 on 2022-07-04 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('csgo', '0008_player_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.pcspec'),
        ),
    ]
