# Generated by Django 4.0.6 on 2022-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorplayer',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
